// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oypgimzaqhxcwklbvlzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cGdpbXphcWh4Y3drbGJ2bHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMjc3NzcsImV4cCI6MjA2MDYwMzc3N30.O87DoL21ZxrObW5luU6QxRDdQzLyjRMIJLLqUBe0jFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);